_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.2
            "8":
                - 2
                - 5
            "12": 0.19.2
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 10
lr:
    value: 0.001
